print("Welcome to the Top Calculator.")
bill = input("What was the total bill? $")
tip = input("What percentage tip would you like to give? 10, 12 or 15? ")
total_tips = float(bill) + (float(bill) * int(tip) / 100)
people = input("How many people to split the bill? ")
total_bill = round(total_tips/int(people), 2)
print(f"Each person should pay: {total_bill}")